server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

pagination:
  default-page: 0
  default-size: 10

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.amqp: DEBUG
    com.rabbitmq.client: DEBUG


# Keycloak and Eureka configurations remain unchanged

spring:
  spring:
    rabbitmq:
      host: localhost
      port: 15672
      username: guest
      password: guest
  application:
    name: product-setup-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydatabase?allowPublicKeyRetrieval=true
#    username: root
#    password: pass
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect